#!/bin/sh

if [ -z ${CROSS_FILE} ]
then
  if [ -z ${NEED_WINE} ]
  then
    CROSS_FILE=/usr/share/mingw/toolchain-mingw64.meson
  else
    CROSS_FILE=/usr/share/mingw/toolchain-mingw64-wine.meson
    MESON_EXE_WRAPPER=/usr/bin/x86_64-w64-mingw64-wine
  fi
fi

exec meson setup \
  --libdir         /usr/x86_64-w64-mingw32/lib \
  --libexecdir     /usr/x86_64-w64-mingw32/lib \
  --bindir         /usr/x86_64-w64-mingw32/bin \
  --sbindir        /usr/x86_64-w64-mingw32/bin \
  --includedir     /usr/x86_64-w64-mingw32/include \
  --datadir        /usr/x86_64-w64-mingw32/share \
  --mandir         /usr/x86_64-w64-mingw32/share/man \
  --infodir        /usr/x86_64-w64-mingw32/share/info \
  --localedir      /usr/x86_64-w64-mingw32/share/locale \
  --sysconfdir     /usr/x86_64-w64-mingw32/etc \
  --localstatedir  /var \
  --sharedstatedir /var/lib \
  --buildtype      release \
  --wrap-mode      nofallback \
  --cross-file ${CROSS_FILE} \
  --default-library shared \
  "$@"
