on:
  workflow_dispatch:

name: Docker images

env:
  REGISTRY: ghcr.io

jobs:
  build-images:
    name: Build & push Docker images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime:
          - name: gtk-latest
            gtktag: main
            adwtag: main
          - name: gtk-4.4
            gtktag: 4.4.1
            adwtag: 1.0.0.alpha.4
          - name: gtk-4.6
            gtktag: 4.6.0
            adwtag: 1.0.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
        with:
          driver-opts: network=host

      - name: Cache Docker layers for the base image
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Write the Dockerfile for the ${{ matrix.runtime.name }} runtime
        run: |
          sed -i 's/%GTKTAG%/${{matrix.runtime.gtktag}}/g' gtk4-cross-base-hub/Dockerfile && sed -i 's/%ADWTAG%/${{matrix.runtime.adwtag}}/g' gtk4-cross-base-hub/Dockerfile

      - name: Build & push the ${{ matrix.runtime.name }} image to Docker Hub
        uses: docker/build-push-action@v2.2.2
        continue-on-error: true
        with:
          allow: security.insecure
          context: ./gtk4-cross-base-hub
          file: ./gtk4-cross-base-hub/Dockerfile
          push: true
          tags: mglolenstine/gtk4-cross:${{ matrix.runtime.name }}
      - name: Write the Dockerfile for the ${{ matrix.runtime.name }} runtime
        run: |
          sed -i 's/%GTKTAG%/${{matrix.runtime.name}}/g' gtk4-cross-rust/Dockerfile
      - name: Build & push the rust${{ matrix.runtime.name }} image to Docker Hub
        uses: docker/build-push-action@v2.2.2
        continue-on-error: true
        with:
          allow: security.insecure
          context: ./gtk4-cross-rust
          file: ./gtk4-cross-rust/Dockerfile
          push: true
          tags: mglolenstine/gtk4-cross:rust-${{ matrix.runtime.name }}

      - name: Login to GitHub Container Repository
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          
      - name: Write the Dockerfile for the ${{ matrix.runtime.name }} runtime
        run: |
          sed -i 's/%GTKTAG%/${{matrix.runtime.gtktag}}/g' gtk4-cross-base-hub/Dockerfile && sed -i 's/%ADWTAG%/${{matrix.runtime.adwtag}}/g' gtk4-cross-base-hub/Dockerfile
      - name: Build & push the ${{ matrix.runtime.name }} image to GitHub Container Repository
        uses: docker/build-push-action@v2.2.2
        continue-on-error: true
        with:
          allow: security.insecure
          context: ./gtk4-cross-base-hub
          file: ./gtk4-cross-base-hub/Dockerfile
          push: true
          tags: ghcr.io/mglolenstine/gtk4-cross:${{ matrix.runtime.name }}
      - name: Write the Dockerfile for the ${{ matrix.runtime.name }} runtime
        run: |
          sed -i 's/%GTKTAG%/${{matrix.runtime.name}}/g' gtk4-cross-rust/Dockerfile
      - name: Build & push the rust${{ matrix.runtime.name }} image to GitHub Container Repository
        uses: docker/build-push-action@v2.2.2
        continue-on-error: true
        with:
          allow: security.insecure
          context: ./gtk4-cross-rust
          file: ./gtk4-cross-rust/Dockerfile
          push: true
          tags: ghcr.io/mglolenstine/gtk4-cross:rust-${{ matrix.runtime.name }}
